---
- name: create systemd directory
  file:
    path: "{{ item }}"
    mode: 0755
    state: directory
  with_items:
    - '~/.config/systemd'
    - '~/.config/systemd/user'
    - '~/.config/environment.d'
