---
- name: create xdg base directory
  file:
    path: "{{ item }}"
    mode: 0755
    state: directory
  with_items:
    - '~/.config'
    - '~/.cache'
    - '~/.local'
    - '~/.local/share'

- name: install ~/.profile
  copy:
    src: profile
    dest: ~/.profile
