---
- name: create ~/.config/git directory
  file:
    path: ~/.config/git
    mode: 0755
    state: directory

- name: install gitconfig
  copy:
    src: config
    dest: ~/.config/git/config

- name: install .zshrc.d/git
  copy:
    src: zshrc.d/git
    dest: ~/.config/zsh/.zshrc.d/git
