---
- name: create xdg base directory and systemd directory
  file:
    path: "{{ item }}"
    mode: 0755
    state: directory
  with_items:
    - ~/.config
    - ~/.config/systemd
    - ~/.config/systemd/user
    - ~/.config/environment.d
    - ~/.cache
    - ~/.local
    - ~/.local/share

- name: install ~/.profile
  copy:
    src: profile
    dest: ~/.profile

- name: install ~/.config/environment.d/xdg.conf
  copy:
    src: xdg.conf
    dest: ~/.config/environment.d/xdg.conf
